spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://localhost:8888
    gateway:
      routes:
        - id: service-a1
          uri: lb://A1
          predicates:
            - Path=/a1/**
        - id: service-a2
          uri: lb://A2
          predicates:
            - Path=/a2/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
