spring:
  application:
    name: gateway
    url: http://localhost:8080
  cloud:
    config:
      uri: http://localhost:8888
    gateway:
      routes:
        - id: service-a1
          uri: http://localhost:8083
          predicates:
            - Path=/a1/**
        - id: service-a2
          uri: http://localhost:8084
          predicates:
            - Path=/a2/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
