spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:

        - id: ServiceA1
          uri: lb://ServiceA1

          predicates:
            - Path=/a1/**


        - id: ServiceB1
          uri: lb://ServiceB1
          predicates:
            - Path=/a1/students-b1/**
          filters:
            - RewritePath=/a1/students-b1/(?<segment>.*), /students/${segment}

        - id: ServiceA2
          uri: lb://ServiceA2

          predicates:
            - Path=/a2/**

        - id: ServiceB2
          uri: lb://ServiceB2
          predicates:
            - Path=/a2/students-b2/**
          filters:
            - RewritePath=/a2/students-b2/(?<segment>.*), /students/${segment}

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
